create table public.events (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  description text null,
  start_date date,
  end_date date,
  start_time text,
  end_time text,
  event_type text check (event_type in ('virtual', 'offline')),
  meeting_link text,
  location text,
  image_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  updated_at timestamp with time zone default timezone('utc'::text, now()),
  location_link text,
  venue_name text,
  address_line1 text, 
  city text,
  postal_code text
);
